import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {projects,publications} from '../src/data.mjs';
const root=path.resolve('dist');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?walk(path.join(dir,d.name)):[path.join(dir,d.name)])}
const files=walk(root),html=files.filter(f=>f.endsWith('.html'));
test('Every project has a dedicated route and project description; commerce demo is deferred',()=>{assert.equal(projects.length,12);for(const p of projects){const text=fs.readFileSync(path.join(root,'work',p.id,'index.html'),'utf8');assert.ok(text.includes(p.description));assert.ok(!text.includes('My contribution'));assert.ok(p.id==='ecommerce'?text.includes('A working storefront'): /data-(demo|research)=/.test(text));if(p.limit)assert.ok(text.includes(p.limit))}});
test('All local links, fragment targets, scripts and images resolve',()=>{for(const file of html){const source=fs.readFileSync(file,'utf8');for(const match of source.matchAll(/(?:href|src)="([^"<>]+)"/g)){const ref=match[1];if(!ref.startsWith('/')&&!ref.startsWith('#'))continue;const [pathname,fragment]=ref.split('#');let target=pathname?path.join(root,decodeURIComponent(pathname)):file;if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');assert.ok(fs.existsSync(target),`${file}: missing ${ref}`);if(fragment)assert.ok(fs.readFileSync(target,'utf8').includes(`id="${fragment}"`),`${file}: missing fragment ${ref}`)}}});
test('Public build excludes source documents, archives and private material',()=>{for(const file of files){assert.ok(!/reference-materials|\.docx$|\.ipynb$|\.zip$|\.env|manuscript\.pdf$|resume-source/i.test(file),file)}const joined=html.map(f=>fs.readFileSync(f,'utf8')).join('');assert.ok(!/PRIVATE KEY|service_account|api_key/i.test(joined));assert.ok(!joined.includes('data-srcdoc'));assert.ok(!joined.includes('78% improvement'))});
test('Publications have author lists, external references and downloadable citations',()=>{assert.equal(publications.length,6);for(const p of publications){assert.ok(p.authors.includes('Gandhi'));assert.ok(p.url.startsWith('https://'));assert.ok(fs.existsSync(path.join(root,'citations',p.id+'.txt')))}});
test('No eager third-party frames or fonts; all CSS assets exist',()=>{for(const file of html)assert.ok(!fs.readFileSync(file,'utf8').includes('<iframe'));const css=fs.readFileSync(path.join(root,'style.css'),'utf8');for(const [,url]of css.matchAll(/url\('([^']+)'\)/g))assert.ok(fs.existsSync(path.join(root,url)),url)});
test('Static pages retain primary content and landmark accessibility',()=>{for(const f of html){const s=fs.readFileSync(f,'utf8');assert.equal((s.match(/<h1[ >]/g)||[]).length,1,f);assert.ok(s.includes('lang="en"'));assert.ok(s.includes('Skip to content'));assert.ok(s.includes('<main id="main">'));assert.ok(s.includes('rel="canonical"'));for(const img of s.matchAll(/<img\b[^>]*>/g))assert.ok(/alt="[^"]*"/.test(img[0]),f)}});
