import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function setup(apiReady=true){
 class El{constructor(){this.events={};this.dataset={};this.value='0';this.attrs={};this.children=[];this.classList={remove(){}}}addEventListener(n,f){(this.events[n]??=[]).push(f)}emit(n){for(const f of this.events[n]||[])f({target:this})}set innerHTML(value){this.html=value;this.nodes={};this.children=[]}get innerHTML(){return this.html||''}querySelector(s){return(this.nodes??={})[s]??=((new El()))}append(el){this.children.push(el)}remove(){this.removed=true}}
 const root=new El(),host=new El(),select=new El(),direct=new El(),doc=new El(),win=new El();root.querySelector=s=>({'[data-choice]':select,'.video-host':host,'[data-video-link]':direct})[s];doc.querySelector=s=>s==='[data-demo="video"]'?root:null;doc.createElement=()=>new El();doc.head=new El();
 let id=0;const timers=new Map(),players=[];if(apiReady)win.YT={Player:class{constructor(frame,config){this.frame=frame;this.events=config.events;players.push(this)}destroy(){this.destroyed=true}}};
 vm.runInNewContext(fs.readFileSync('src/video-player.js','utf8'),{document:doc,window:win,location:{origin:'http://127.0.0.1:4321',href:'http://127.0.0.1:4321/work/stock-research/'},URLSearchParams,setTimeout:(f,delay)=>{assert.equal(delay,12000);timers.set(++id,f);return id},clearTimeout:i=>timers.delete(i)});
 return{host,select,direct,doc,win,timers,players,async play(){host.querySelector('[data-play]').emit('click');await Promise.resolve();await Promise.resolve()},timeout(){const [i,fn]=timers.entries().next().value;timers.delete(i);fn()}};
}
test('YouTube is lazy, carries the actual origin and waits for real player readiness',async()=>{const h=setup();assert.equal(h.players.length,0);await h.play();assert.equal(h.players.length,1);const p=h.players[0];assert.match(p.frame.src,/youtube.com\/embed\/oQRW5Dpfwks/);assert.match(p.frame.src,/origin=http%3A%2F%2F127.0.0.1%3A4321/);assert.equal(p.frame.referrerPolicy,'strict-origin-when-cross-origin');assert.equal(h.host.dataset.playerPhase,'iframe-loading');p.events.onReady();assert.equal(h.host.dataset.playerPhase,'ready');assert.equal(h.timers.size,0)});
test('A stalled player produces a visible selected-recording fallback; stale callbacks cannot replace a new selection',async()=>{const h=setup();h.select.value='1';h.select.emit('change');await h.play();const old=h.players[0];h.timeout();assert.match(h.host.innerHTML,/did not respond/);assert.match(h.host.innerHTML,/y-gy7XYQpDQ/);assert.equal(old.destroyed,true);h.select.value='2';h.select.emit('change');old.events.onReady();assert.match(h.host.innerHTML,/Android/);assert.match(h.direct.href,/24KB_DL01Nw/)});
test('Blocked API script and explicit YouTube embedding errors have distinct fallbacks',async()=>{const blocked=setup(false);await blocked.play();blocked.timeout();assert.match(blocked.host.innerHTML,/did not finish loading/);const denied=setup();await denied.play();denied.players[0].events.onError({data:153});assert.match(denied.host.innerHTML,/identification/);assert.equal(denied.timers.size,0)});
