import {analyticsFooter,analyticsPanel,privacyContent} from '../src/analytics-ui.mjs';
import {projectFilm,projectFilms} from '../src/project-films.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {projects,publications} from '../src/data.mjs';
import {demo} from '../src/demos.mjs';
const out=path.resolve('dist');
if(out!==path.join(process.cwd(),'dist'))throw Error('Unexpected build directory');
fs.rmSync(out,{recursive:true,force:true});
fs.mkdirSync(out,{recursive:true});
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const write=(file,body)=>{const p=path.join(out,file);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,body)};
fs.cpSync('public',out,{recursive:true});
for(const file of ['style.css','app.js','research-demos.js','peptide-film.js','project-films.js','video-player.js','analytics.js'])fs.copyFileSync(`src/${file}`,path.join(out,file));
const routes=[];
const nav=[['Work','/work/'],['Publications','/publications/'],['About','/about/'],['Writing','/writing/'],['Contact','/contact/']];
function page(route,title,body,description='Yash Gandhi — AI engineer and researcher. Models, agentic workflows and applications across language, vision, forecasting and science.'){
routes.push(route);write(route==='/'?'index.html':route.slice(1)+'index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="color-scheme" content="light dark"><title>${esc(title)} · Yash Gandhi</title><link rel="canonical" href="https://yash4gandhi.github.io${route}"><meta property="og:title" content="${esc(title)} · Yash Gandhi"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://yash4gandhi.github.io${route}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/analytics.js" defer></script><script src="/app.js" defer></script><script src="/research-demos.js" defer></script>${route==='/work/peptide-design/'?'<script src="/peptide-film.js" defer></script>':''}${projectFilms[route.split('/')[2]]?'<script src="/project-films.js" defer></script>':''}${route==='/work/stock-research/'?'<script src="/video-player.js" defer></script>':''}<meta name="referrer" content="strict-origin-when-cross-origin"></head><body data-analytics-page="${esc(route)}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="/">Yash Gandhi<span>.</span></a><nav aria-label="Main navigation">${nav.map(([n,u])=>`<a href="${u}" ${route.startsWith(u)?'aria-current="page"':''}>${n}</a>`).join('')}</nav><button class="theme" aria-label="Switch to dark theme" data-theme>◐</button></header><main id="main">${body}</main><footer><div><a class="wordmark" href="/">Yash Gandhi<span>.</span></a><p>Curiosity, carried through to implementation.</p></div><div><a href="/contact/">Let’s connect ↗</a><a href="https://github.com/yash4gandhi">GitHub ↗</a><a href="/resume/">Résumé</a></div><p class="fine">AI engineering · Research · Software systems</p>${analyticsFooter}</footer>${analyticsPanel}<dialog data-lightbox aria-label="Enlarged research figure"><button data-close>Close ×</button><img alt=""><p></p></dialog></body></html>`);
}
const row=(p,i)=>`<article class="project-row" data-category="${p.category}"><span class="row-number">${String(i+1).padStart(2,'0')}</span><div><p class="eyebrow">${p.category}</p><h3><a href="/work/${p.id}/">${p.title}<span aria-hidden="true">↗</span></a></h3><p>${p.summary}</p><span class="fine">${p.tags}</span></div></article>`;
const slides=[['Agentic AI','financial-analyst','“How much did revenue grow?”','<div class="mini-flow"><span>01 Retrieve</span><span>02 Plan</span><span>03 Calculate</span><span>04 Verify</span></div><div class="hero-equation"><small>REPORT EVIDENCE → CHECKED ARITHMETIC</small><span>128.4 − 112.0 <b>= 16.4m</b></span></div>','Fictional Northstar report · illustrative workflow'],['Computer vision','tem-denoising','From noisy images to structural insight.','<img class="hero-tem" src="/assets/tem-pair.png" alt="Conference TEM before and after panels with 1 nm scale bars"><p class="fine">Before (a) / After (b) · Poerwoprajitno, Gandhi et al.</p>','Research figure · M&M conference abstract, 2025'],['Generative AI for science','peptide-design','Explore the space between known sequences.','<div class="hero-peptide" aria-hidden="true">'+[...'IDTNVILNYKKAADHFSIFM'].map(c=>`<i>${c}</i>`).join('')+'</div><div class="mini-flow"><span>DDIM generation</span><span>CfC prediction</span><span>Research tools</span></div>','Saved DDIM-HTSK1 candidate · initial M omitted'],['Backend engineering','alation-cms','One source. Many internal services.','<div class="hero-architecture"><span>Internal clients</span><b>↓ gRPC</b><strong>Configuration service</strong><b>↓</b><span>PostgreSQL / Redis</span></div>','High-level architecture · fictional tenant context']];
page('/','AI engineer & researcher',`<section class="hero"><div class="hero-copy"><p class="eyebrow">Yash Gandhi / <strong>AI Engineer</strong> & researcher</p><h1>I build<br><em>AI systems.</em></h1><p class="lead">I develop machine learning models, build agentic workflows, and engineer the applications that bring them into use.</p><p class="intro">My work spans language, vision, and forecasting, including applications in science.</p><div class="actions"><a class="button primary" href="/work/">Explore my work <span>↗</span></a><a href="/about/#experience">My experience →</a></div></div><section class="carousel" data-carousel aria-roledescription="carousel" aria-label="Featured work across AI and engineering">${slides.map(([label,id,title,visual,note],i)=>`<div class="slide" data-slide ${i?'hidden':''} role="group" aria-roledescription="slide" aria-label="${i+1} of 4: ${label}"><div class="slide-inner"><p class="eyebrow">${label}<span>0${i+1} / 04</span></p><h2>${title}</h2>${visual}<p class="fine slide-note">${note}</p></div><a class="slide-link" href="/work/${id}/">${projects.find(p=>p.id===id).title}<span>Explore project ↗</span></a></div>`).join('')}<div class="carousel-controls"><div aria-label="Choose featured project">${slides.map(([label],i)=>`<button data-slide-to="${i}" aria-label="Show ${label}" aria-pressed="${i===0}">0${i+1}</button>`).join('')}</div><button data-prev aria-label="Previous featured project">←</button><button data-pause aria-label="Pause automatic project rotation">Pause</button><button data-next-slide aria-label="Next featured project">→</button></div><p class="sr-only" data-carousel-status aria-live="polite"></p></section></section><div class="capabilities"><span>Machine learning</span><span>Agentic AI & NLP</span><span>Computer vision</span><span>AI for science</span><span>Backend systems</span></div><section class="section"><div class="section-head"><div><p class="eyebrow">A few ways I work</p><h2>Selected work</h2></div><a href="/work/">All 12 projects ↗</a></div>${projects.slice(0,4).map(row).join('')}</section><section class="closing"><p class="eyebrow">Research at USC · Engineering at Alation & Empays</p><h2>From a promising idea<br>to a <em>useful system.</em></h2><a href="/about/">The experience behind the work →</a></section>`);
page('/work/','Work',`<section class="page-head"><p class="eyebrow">Selected experiments & built systems</p><h1>Ideas, put<br><em>to work.</em></h1><p class="lead">Twelve projects across AI, research and software engineering. Open a project to explore the decisions, evidence and an interactive demonstration.</p></section><div class="filters" role="group" aria-label="Filter projects">${['All','Agentic AI','Computer vision','AI for science','Software systems'].map((c,i)=>`<button data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><p class="fine" data-filter-count role="status">12 projects</p><section aria-label="Projects">${projects.map(row).join('')}</section>`);
for(const [i,p] of projects.entries())page(`/work/${p.id}/`,p.title,`<div class="breadcrumb"><a href="/work/">← All work</a><span>${p.category}</span></div><section class="project-head"><p class="eyebrow">${p.tags}</p><h1>${p.title}</h1><p class="lead">${p.line}</p><p>${p.summary}</p></section><div class="project-intro"><h2>Summary</h2><p>${p.description}</p></div>${p.concepts?`<section class="concepts" aria-label="Key concepts">${p.concepts.map(([name,text])=>`<article><h3>${name}</h3><p>${text}</p></article>`).join('')}</section>`:''}<section class="demo-section"><div class="section-head"><h2>Explore the project</h2><span class="fine">Interactive field notes</span></div>${projectFilm(p.id)}${demo(p.id)}</section><div class="project-details"><section><p class="eyebrow">Under the surface</p><h2>How it works</h2><p>${p.detail}</p></section><section><p class="eyebrow">What it adds</p><h2>Outcome & context</h2><p>${p.outcome}</p>${p.limit?`<p class="context-note">${p.limit}</p>`:''}</section></div>${p.pub.length?`<section class="related"><h2>Related publication</h2>${p.pub.map(id=>{const r=publications.find(x=>x.id===id);return `<a href="/publications/#${id}">${r.title} ↗</a><p class="fine">${r.venue} · ${r.year} · ${r.status}</p>`}).join('')}</section>`:''}<div class="next-project"><span class="eyebrow">Continue exploring</span><a href="/work/${projects[(i+1)%projects.length].id}/">${projects[(i+1)%projects.length].title} →</a></div>`,p.summary);
page('/publications/','Publications',`<section class="page-head"><p class="eyebrow">Research, in the record</p><h1>Published work<br>& <em>open questions.</em></h1><p class="lead">Collaborative research across scientific ML, language and computer vision.</p></section>${publications.map(p=>`<article id="${p.id}" class="publication"><div><span class="eyebrow">${p.year}</span><p class="badge">${p.status}</p></div><div><h2><a href="${p.url}">${p.title} ↗</a></h2><p>${p.authors}</p><p class="fine">${p.venue}</p><div class="actions"><a href="/work/${p.project}/">Explore the project →</a><a href="/citations/${p.id}.txt" download>Download citation</a></div></div></article>`).join('')}<section class="section"><p class="eyebrow">In preparation · publication status unconfirmed</p><h2>Ongoing research</h2><p>Integrating Diffusion and Liquid AI Models for Predicting Peptide Affinity from mRNA Display Selections.</p><p>Leveraging Liquid AI for Oil Production Forecasting.</p><p class="fine">Manuscripts are not offered as public downloads.</p></section>`);
for(const p of publications)write(`citations/${p.id}.txt`,`${p.authors}. (${p.year}). ${p.title}. ${p.venue}. ${p.status}.\n${p.url}\n`);
const entry=(date,title,text)=>`<article class="timeline-entry"><p class="eyebrow">${date}</p><div><h3>${title}</h3><p>${text}</p></div></article>`;
page('/about/','About',`<section class="page-head"><p class="eyebrow">Engineer, researcher, collaborator</p><h1>Building with<br><em>curiosity.</em></h1><p class="lead">I’m Yash Gandhi, an AI engineer and researcher working across machine learning, agentic applications and software systems.</p><p class="about-copy">My work connects model development with the applications that make it useful: a research portal for scientific imaging, tools for peptide design, evidence-driven financial analysis and infrastructure for internal services.</p></section><section id="experience" class="section"><h2>Experience</h2>${entry('July 2023–present','Research Engineer · USC','Center for Advanced Computing and Simulations. Computational work in TEM denoising, peptide generation and affinity, oil forecasting and methane modeling. <a href="/work/">Explore the projects →</a>')}${entry('May–August 2022','Software Engineering Intern · Alation','Owned the customer configuration management service supporting provisioning, tier changes and a multitenant migration. <a href="/work/alation-cms/">View the system →</a>')}${entry('March–August 2020','Software Engineering Intern · Empays','Built a conversational banking interface across Dialogflow, Flask and the frontend. <a href="/work/banking-assistant/">Explore the workflow →</a>')}</section><section class="section"><h2>Education</h2>${entry('August 2021–May 2023','MS, Computer Science · University of Southern California','Selected coursework: Machine Learning for Data Science, Information Retrieval and Web Search Engines, Algorithms, Database Systems, Web Development Technologies.')}${entry('August 2017–May 2021','BTech, Information Technology · Sardar Patel Institute of Technology','Selected coursework: Distributed Systems, Machine Learning, Digital Image Processing, Software Engineering and User Experience and Design.')}</section><section class="section"><h2>Community & mentorship</h2>${entry('November 2021–August 2022','Mentor · USC Viterbi School of Engineering','Helped incoming graduate students navigate the transition to USC and Los Angeles through meetings and academic and personal guidance.')}${entry('July 2019–July 2020','Administrator · ITSA S.P.I.T.','Organized programming workshops and coordinated technical and recreational activities, including treks and excursions.')}${entry('September 2018–January 2020','Volunteer Tutor · Abhyudaya–SPJIMR','Tutored mathematics and science and mentored students in grades 7–10 from economically disadvantaged backgrounds.')}</section><div class="actions"><a class="button primary" href="/contact/">Get in touch ↗</a><a href="/resume/">Résumé →</a></div>`);
page('/contact/','Contact',`<section class="page-head"><p class="eyebrow">Start a conversation</p><h1>Let’s build<br><em>something useful.</em></h1><p class="lead">Get in touch about AI engineering, research or software systems.</p><div class="actions"><a class="button primary" href="mailto:yash4gandhi@gmail.com">Email me ↗</a><a href="/downloads/Resume_Yash_Gandhi.pdf" download>Download résumé (PDF) ↓</a></div></section><section class="contact-details" aria-label="Contact details"><div><p class="eyebrow">Email</p><a href="mailto:yash4gandhi@gmail.com">yash4gandhi@gmail.com</a></div><div><p class="eyebrow">Phone</p><a href="tel:+918169471348">+91 81694 71348</a></div><div><p class="eyebrow">LinkedIn</p><a href="https://www.linkedin.com/in/yash4gandhi/">Yash Gandhi ↗</a></div><div><p class="eyebrow">GitHub</p><a href="https://github.com/yash4gandhi">yash4gandhi ↗</a></div></section>`);
page('/resume/','Résumé',`<section class="page-head"><p class="eyebrow">Experience at a glance</p><h1>Résumé<em>.</em></h1><p class="lead">AI engineering, research and software development.</p><p>Download my résumé for an overview of my experience, projects and technical skills.</p><div class="actions"><a class="button primary" href="/downloads/Resume_Yash_Gandhi.pdf" download>Download résumé (PDF) ↓</a><a href="/downloads/Resume_Yash_Gandhi.pdf" target="_blank" rel="noopener noreferrer">View PDF ↗</a></div><div class="actions"><a href="/about/#experience">Read my experience →</a><a href="/publications/">Publications →</a></div></section>`);
// Author-controlled Markdown: no HTML is accepted; unpublished drafts never enter dist.
function markdown(raw){return raw.split(/\n\s*\n/).map(block=>{const b=block.trim();if(b.startsWith('### '))return `<h3>${esc(b.slice(4))}</h3>`;if(b.startsWith('## '))return `<h2>${esc(b.slice(3))}</h2>`;return `<p>${esc(b).replaceAll('\n','<br>')}</p>`}).join('')}
const posts=[];
for(const file of fs.readdirSync('content/writing').filter(x=>x.endsWith('.md'))){const raw=fs.readFileSync(`content/writing/${file}`,'utf8');const match=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);if(!match)continue;const meta=Object.fromEntries(match[1].split(/\r?\n/).map(l=>{const i=l.indexOf(':');return [l.slice(0,i).trim(),l.slice(i+1).trim()]}));if(meta.published!=='true')continue;const slug=file.replace(/\.md$/,'');if(!/^[a-z0-9-]+$/.test(slug))throw Error('Invalid writing slug');posts.push({...meta,slug});page(`/writing/${slug}/`,meta.title,`<article class="prose"><a href="/writing/">← Writing</a><p class="eyebrow">${esc(meta.date||'')}</p><h1>${esc(meta.title)}</h1>${markdown(match[2])}</article>`)}
page('/writing/','Writing',`<section class="page-head"><p class="eyebrow">Notes from the workbench</p><h1>Thinking<br><em>out loud.</em></h1><p class="lead">A home for technical notes on models, systems and the decisions between them.</p></section>${posts.length?posts.map(p=>`<article class="publication"><span>${esc(p.date)}</span><h2><a href="/writing/${p.slug}/">${esc(p.title)} →</a></h2></article>`).join(''):'<section class="empty-state"><span class="eyebrow">The first page is still open</span><h2>No essays published yet.</h2><p>In the meantime, the project pages share the methods, implementation choices and evidence behind my work.</p><a href="/work/">Explore the project notes →</a></section>'}`);
page('/404/','Page not found',`<section class="page-head"><p class="eyebrow">404</p><h1>A different<br><em>direction.</em></h1><p>This page could not be found.</p><a class="button primary" href="/">Back to home →</a></section>`);fs.copyFileSync(path.join(out,'404/index.html'),path.join(out,'404.html'));
page('/privacy/','Privacy & analytics',privacyContent);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.filter(r=>r!='/404/').map(r=>`<url><loc>https://yash4gandhi.github.io${r}</loc></url>`).join('')}</urlset>`);
write('robots.txt','User-agent: *\nAllow: /\nSitemap: https://yash4gandhi.github.io/sitemap.xml\n');write('.nojekyll','');
console.log(`Built ${routes.length} routes. Public assets only; no deployment performed.`);

