const $=(s,r=document)=>r?.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const theme=$('[data-theme]');
function setTheme(dark){document.body.classList.toggle('dark',dark);theme?.setAttribute('aria-label',`Switch to ${dark?'light':'dark'} theme`)}
try{setTheme(localStorage.getItem('portfolio-theme')==='dark')}catch{}
theme?.addEventListener('click',()=>{const dark=!document.body.classList.contains('dark');setTheme(dark);try{localStorage.setItem('portfolio-theme',dark?'dark':'light')}catch{}});
const carousel=$('[data-carousel]');
if(carousel){
 const slides=$$('[data-slide]',carousel),selectors=$$('[data-slide-to]',carousel),motion=matchMedia('(prefers-reduced-motion: reduce)');
 let active=0,paused=motion.matches,hover=false,visible=false,timer=null,startX=null;
 const pause=$('[data-pause]',carousel);
 function schedule(){clearTimeout(timer);if(!paused&&!hover&&visible&&!document.hidden)timer=setTimeout(()=>{show((active+1)%slides.length,false);schedule()},7000)}
 function updatePause(){pause.textContent=paused?'Play':'Pause';pause.setAttribute('aria-label',`${paused?'Play':'Pause'} automatic project rotation`);schedule()}
 function stop(){paused=true;updatePause()}
 function show(i,manual=true){active=(i+slides.length)%slides.length;slides.forEach((s,j)=>{s.hidden=j!==active});selectors.forEach((b,j)=>b.setAttribute('aria-pressed',String(j===active)));if(manual){stop();$('[data-carousel-status]',carousel).textContent=slides[active].getAttribute('aria-label')}}
 selectors.forEach((b,i)=>b.addEventListener('click',()=>show(i)));
 $('[data-prev]',carousel).addEventListener('click',()=>show(active-1));$('[data-next-slide]',carousel).addEventListener('click',()=>show(active+1));
 let pointerPauseIntent=null;
 pause.addEventListener('pointerdown',()=>{pointerPauseIntent=!paused});
 pause.addEventListener('click',()=>{paused=pointerPauseIntent??!paused;pointerPauseIntent=null;updatePause()});
 carousel.addEventListener('focusin',stop);carousel.addEventListener('mouseenter',()=>{hover=true;schedule()});carousel.addEventListener('mouseleave',()=>{hover=false;schedule()});
 carousel.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(active+(e.key==='ArrowRight'?1:-1))}});
 carousel.addEventListener('touchstart',e=>{startX=e.touches[0].clientX},{passive:true});carousel.addEventListener('touchend',e=>{if(startX!==null&&Math.abs(e.changedTouches[0].clientX-startX)>55)show(active+(e.changedTouches[0].clientX<startX?1:-1));startX=null},{passive:true});
 new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;schedule()},{threshold:.25}).observe(carousel);
 document.addEventListener('visibilitychange',schedule);window.addEventListener('pagehide',()=>clearTimeout(timer));motion.addEventListener('change',()=>{if(motion.matches)stop()});updatePause();
}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const selected=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;$$('[data-category]').forEach(p=>{p.hidden=selected!=='All'&&p.dataset.category!==selected;if(!p.hidden)count++});$('[data-filter-count]').textContent=`${count} project${count===1?'':'s'}`;}));
const stateMessages={
 cms:[['An internal service requests configuration for fictional tenant atlas-demo.','Resolve the tenant-scoped request through the gRPC service. Redis caches support access at client/server level.','Read the customer configuration from PostgreSQL/RDS when needed. This diagram does not prescribe cache invalidation semantics.','Return the tenant-scoped configuration to the internal client.'],['Prepare a new-customer configuration for fictional tenant atlas-demo.','Validate the request within the configuration service.','Persist the new configuration. The encryption microservice is part of the confirmed stack; exact sequencing is not illustrated.','The new configuration can support downstream provisioning.'],['Request a Standard → Enterprise tier change for fictional tenant atlas-demo.','Resolve the tenant and requested configuration change.','Persist the requested tier configuration. No exact cache-coherence mechanism is claimed.','Return the updated configuration: Enterprise.']],
 bank:[['“Show my last 3 transactions.”','Intent: recent_transactions\nSlots: count = 3; account = DEMO-01','Filter fictional records by account; order newest first; limit 3.','16 Jan · Coffee · ₹180\n14 Jan · Books · ₹1,450\n11 Jan · Transit · ₹320'],['“Show transactions above ₹1,000.”','Intent: amount_filter\nSlots: comparison = above; amount = 1000','Filter fictional account DEMO-01 where amount > ₹1,000.','14 Jan · Books · ₹1,450\n05 Jan · Groceries · ₹2,100'],['“Show transactions from January.”','Intent: date_filter\nSlots: month = January; year = missing','Missing-slot help: Which year do you mean?\nPrepared reply: 2026. Then apply the date range.','January 2026 · 4 fictional transactions\nTotal debits: ₹4,050'],['“Check transaction TX-DEMO-14.”','Intent: transaction_status\nSlots: id = TX-DEMO-14','Look up the fictional transaction status record.','TX-DEMO-14 · Books · ₹1,450 · Completed']],
 claims:[['“The city library opens on Sunday.”','Keywords: city · library · Sunday','Fictional source A: “City library adds Sunday opening hours.”\nFictional source B: “Library membership rules updated.”','Source A concerns the same opening-hours claim. Retrieval identifies evidence to inspect; it does not independently establish truth.'],['“The city library is free for everyone.”','Keywords: city · library · free','Fictional source: “Library waives membership fees for students.”','A related article is narrower than the claim. Similar words do not support “everyone.” An absent supporting match is not proof of falsehood.']],
 english:[['Topic: a recent project.\nQuestion: What did you build, and what did you learn?','“Last month I build a model. It help me understand data.”','build → built: past-tense context\nhelp → helped: keep the tense consistent\n“Last month I built a model. It helped me understand data.”','Illustrative speech report\nSpeaking duration: 20 s · Syllables: 42\nPauses: 3 · Speaking rate: 2.1 syllables/s\nPractice focus: consistent past tense.'],['Topic: a favorite place.\nQuestion: Why do you enjoy going there?','“The gardens is quiet. I goes there on weekends.”','is → are: plural subject agreement\ngoes → go: first-person agreement\n“The gardens are quiet. I go there on weekends.”','Illustrative speech report\nSpeaking duration: 15 s · Syllables: 30\nPauses: 2 · Speaking rate: 2.0 syllables/s\nPractice focus: subject–verb agreement.']]
};
const plain=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
for(const root of $$('[data-demo]')){
 const kind=root.dataset.demo,select=$('[data-choice]',root),output=$('[data-output]',root);let stage=0,choice=0;
 function render(){
  $$('[data-step]',root).forEach((s,i)=>{if(i===stage)s.setAttribute('aria-current','step');else s.removeAttribute('aria-current')});
  if($('[data-position]',root))$('[data-position]',root).textContent=`${stage+1} / 4`;
  if($('[data-back]',root))$('[data-back]',root).disabled=stage===0;
  if($('[data-next]',root))$('[data-next]',root).disabled=stage===3;
  if(stateMessages[kind]){const msg=stateMessages[kind][choice][stage];output.innerHTML=`<strong>${['Input','Interpretation','Processing','Result'][stage]}</strong><p>${plain(msg).replaceAll('\n','<br>')}</p>`;if($('[data-question]',root))$('[data-question]',root).textContent=stateMessages[kind][choice][kind==='english'&&stage>0?1:0];if(kind==='cms')$('[data-tier]',root).textContent=choice===2&&stage===3?'Enterprise':'Standard'}
 }
 if($('[data-next]',root)){$('[data-next]',root).addEventListener('click',()=>{stage=Math.min(stage+1,3);render()});$('[data-back]',root).addEventListener('click',()=>{stage=Math.max(stage-1,0);render()});$('[data-reset]',root).addEventListener('click',()=>{stage=0;render()});select?.addEventListener('change',()=>{choice=Number(select.value);stage=0;render()});render()}
 if(kind==='tem'){$('[data-compare]',root).addEventListener('input',e=>$('.comparison',root).style.setProperty('--split',`${e.target.value}%`));$$('[data-frame]',root).forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.frame);$$('[data-frame]',root).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.frame-focus img',root).style.transform=`translate(-150px,-${[38,179,320][n]}px)`;$('[data-frame-caption]',root).textContent=n===0?'At 3 s, the source caption identifies a defect at the red arrow.':`At ${n===1?6:15} s, the source caption reports that the identified defect is absent.`}))}
 if(kind==='oil'){let model=0;const sites=['BEAP','BEAT','EUAT','EUZE'];const update=()=>{const n=Number(select.value);$('[data-oil-image]',root).src=`/assets/oil-${n+6}.png`;$('[data-oil-image]',root).alt=`${sites[n]} source figure: history and Informer/LTC predictions, axes preserved`;$('[data-oil-caption]',root).textContent=`${sites[n]} · supplied manuscript Figure ${n+6}. Yellow: prediction; orange: ground truth.`;output.textContent=['A/B: historical record and Informer forecast. C/D: LTC input sample and forecast. Panel time axes and normalization differ.','Panel B: Informer prediction with its own calendar-time axis. Percentile selection: 70th for EUAT, 80th for BEAP, BEAT and EUZE. Read alongside panel A.','Panel D: LTC prediction plotted against timesteps. Panel C shows its input/forecast context. The manuscript describes a 200-step input and 45-step horizon.'][model]};select.addEventListener('change',update);$$('[data-model]',root).forEach(b=>b.addEventListener('click',()=>{model=Number(b.dataset.model);$$('[data-model]',root).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update()}));}
 if(kind==='methane'){let task=0;const update=()=>{const labels=task?['CFD simulations','Generated sequences','Offline ML analysis']:['Canopy & sensor','Recorded data','Offline ML analysis']; $$('.architecture > div',root).forEach((el,i)=>el.textContent=labels[i]);const n=Number(select.value),fig=task?[13,11,12][n]:[9,10][n],name=task?['LTC','LSTM','FFN'][n]:['LTC','LSTM'][n];$('[data-methane-image]',root).src=`/assets/methane-${fig}.png`;$('[data-methane-image]',root).alt=`${task?'CFD':'Field'} ${name} source plot, original axes retained`;$('[data-methane-caption]',root).textContent=task?`CFD source Figure ${fig} · ${name} according to manuscript narrative. Model naming follows the plot title; some manuscript captions incorrectly repeat FFN. Axis units differ across source figures (FFN: mol/m³; LSTM/LTC: ppm). The LSTM ppm scale exceeds 1e6 and requires clarification; do not compare absolute concentrations across these plots.`:`Field measurements · Figure ${fig} · ${name} according to source caption. Axes and scaling retained as supplied; no units are inferred.`;output.textContent=task?'CFD-generated data is separate from field measurements. Original source figure only; no gas physics is simulated here. Model naming follows the surrounding manuscript narrative, with caption inconsistencies disclosed.':'Approximately four operational hours at one well. Surge timing is more closely captured than peak magnitude.'};select.addEventListener('change',update);$$('[data-task]',root).forEach(b=>b.addEventListener('click',()=>{task=Number(b.dataset.task);$$('[data-task]',root).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));select.innerHTML=(task?['LTC','LSTM','FFN']:['LTC','LSTM']).map((x,i)=>`<option value="${i}">${x}</option>`).join('');update()}));}

}
const dialog=$('[data-lightbox]');let trigger=null;
$$('[data-enlarge]').forEach(b=>b.addEventListener('click',()=>{trigger=b;const img=$('img',b);$('img',dialog).src=img.src;$('img',dialog).alt=img.alt;$('p',dialog).textContent=$('figcaption',b.closest('figure'))?.textContent||'';dialog.showModal()}));
$('[data-close]',dialog)?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>trigger?.focus());



