import {financialDemo,peptideDemo,touristDemo} from './research-demos.mjs';
const choices=(name,options)=>`<label class="field">${name}<select data-choice>${options.map((o,i)=>`<option value="${i}">${o}</option>`).join('')}</select></label>`;
const steps=(names)=>`<ol class="steps">${names.map((n,i)=>`<li data-step="${i}" ${i===0?'aria-current="step"':''}><span>0${i+1}</span>${n}</li>`).join('')}</ol>`;
const controls=`<div class="demo-controls"><button data-back disabled>← Previous step</button><span data-position>1 / 4</span><button data-next>Next step →</button><button data-reset>Reset</button></div>`;
const flow=(id,names,body)=>`<div class="demo" data-demo="${id}">${steps(names)}${body}${controls}<p class="fine">Illustrative walkthrough · prepared in your browser · no live model calls</p></div>`;
const figure=(src,alt,caption)=>`<figure><button class="figure-open" data-enlarge aria-label="Enlarge ${alt}"><img src="/assets/${src}" alt="${alt}" loading="lazy"></button><figcaption>${caption}</figcaption></figure>`;
export function demo(id){switch(id){
case 'financial-analyst':return financialDemo();
case 'alation-cms':return flow('cms',['Request','Resolve','Store','Respond'],`${choices('Choose an operation',['Retrieve configuration','Provision a customer','Change a customer tier'])}<div class="tenant-strip"><span>Fictional tenant</span><strong>atlas-demo</strong><span data-tier>Standard</span></div><div class="architecture"><div>Internal service<br><small>gRPC client</small></div><span>→</span><div>Configuration service<br><small>Django</small></div><span>→</span><div>Persistence<br><small>PostgreSQL / RDS</small></div></div><div class="supporting"><span>Redis caches</span><span>Encryption microservice</span><span>Datadog</span></div><div class="readout" aria-live="polite" data-output></div>`);
case 'banking-assistant':return flow('bank',['Question','Intent & slots','Query','Response'],`${choices('Choose a banking question',['Show my last 3 transactions','Show transactions above ₹1,000','Show transactions from January','Check a transaction status'])}<div class="demo-grid"><div class="chat-bubble" data-question></div><div class="readout" aria-live="polite" data-output></div></div><p class="fine">Sample account DEMO-01 · demonstration transactions</p>`);
case 'semantic-claims':return flow('claims',['Claim','Keywords','Retrieve','Interpret'],`${choices('Choose an illustrative claim',['The city library opens on Sunday','The city library is free for everyone'])}<div class="chat-bubble" data-question></div><div class="readout" aria-live="polite" data-output></div><p class="fine">Fictional claims and source cards. No real WhatsApp messages or model-computed similarity scores.</p>`);
case 'english-assistant':return flow('english',['Topic','Answer','Grammar','Report'],`${choices('Choose a practice topic',['A recent project','A favorite place'])}<div class="demo-grid"><div class="chat-bubble" data-question></div><div class="readout" aria-live="polite" data-output></div></div><p class="fine">Prepared example; speech measurements are illustrative, not an assessment of a real speaker.</p>`);
case 'peptide-design':return peptideDemo();
case 'tem-denoising':return `<div class="demo light" data-demo="tem"><h3>Inspect the source, preserve the scale</h3><p>Drag the comparison control, or use its arrow keys. Panel (a) is before denoising; panel (b) is after denoising, as identified in the conference abstract.</p><div class="comparison"><div class="tem-panel before"></div><div class="tem-panel after"></div><span class="compare-line"></span><span class="compare-label left">Before · (a)</span><span class="compare-label right">After · (b)</span></div><label class="field">Comparison position<input type="range" data-compare min="0" max="100" value="50"></label>${figure('tem-pair.png','Original conference before and after TEM panels with 1 nm scale bars','Poerwoprajitno, Gandhi and collaborators, M&M 2025 conference abstract, Figure 2. Full source panels; no clean experimental reference.')}<details><summary>Method comparison and FFT evidence</summary>${figure('tem-methods.png','TEM method comparison with original method headers and FFTs','Supplied research comparison. Use panel headers: c Original, d N2N, e N2F, f N2V, g NLM, h SRD, i BM3D, j R2R. The embedded caption gives conflicting names for some panels; it is retained unaltered. R2R and Original agree between header and caption. No quantitative ranking is inferred.')}</details><h3>Follow a defect through time</h3><div class="evidence-tabs" role="group" aria-label="TEM time frame"><button data-frame="0" aria-pressed="true">3 seconds</button><button data-frame="1" aria-pressed="false">6 seconds</button><button data-frame="2" aria-pressed="false">15 seconds</button></div><div class="frame-focus"><img src="/assets/tem-time.png" alt="Source time series with 2 nm scale bars and enlarged defect regions" loading="lazy"></div><p data-frame-caption aria-live="polite">At 3 s, the source caption identifies a defect at the red arrow.</p><details><summary>View complete time-series source and caption</summary>${figure('tem-time.png','Complete denoised TEM time series at 3, 6 and 15 seconds','Supplied R2R time-series figure. Collaborators supplied experimental data and structural interpretation.')}</details><div class="two-notes"><section><h3>Training</h3><p>Noisy image → paired recorruptions → train DnCNN under the R2R noise assumptions.</p></section><section><h3>Research portal</h3><p>Upload → processing → inference → report with image and FFT analysis. React, S3, Lambda and SageMaker at a high level.</p></section></div></div>`;
case 'oil-forecasting':return `<div class="demo light" data-demo="oil">${choices('Choose an oil-production site',['BEAP','BEAT','EUAT','EUZE'])}<div class="evidence-tabs" role="group" aria-label="Read forecast panels"><button data-model="0" aria-pressed="true">Read all panels</button><button data-model="1" aria-pressed="false">Informer context</button><button data-model="2" aria-pressed="false">LTC context</button></div><figure><button class="figure-open" data-enlarge aria-label="Enlarge oil forecast source figure"><img data-oil-image src="/assets/oil-6.png" alt="BEAP source figure: history and Informer/LTC predictions, axes preserved" loading="lazy"></button><figcaption data-oil-caption>BEAP · supplied manuscript Figure 6. Yellow: prediction; orange: ground truth.</figcaption></figure><div class="readout" data-output aria-live="polite">A/B: historical record and Informer forecast. C/D: LTC input sample and forecast. Panel time axes and normalization differ.</div><p class="fine">Selected figure from the in-preparation liquid-AI manuscript. Explore the original source panels with their time axes and units intact.</p></div>`;
case 'methane-modeling':return `<div class="demo light" data-demo="methane"><div class="evidence-tabs" role="group" aria-label="Methane research task"><button data-task="0" aria-pressed="true">Field measurements</button><button data-task="1" aria-pressed="false">CFD predictions</button></div>${choices('Choose a source figure',['LTC','LSTM'])}<div class="architecture"><div>Canopy & sensor</div><span>→</span><div>Recorded data</div><span>→</span><div>Offline ML analysis</div></div><figure><button class="figure-open" data-enlarge aria-label="Enlarge methane source figure"><img data-methane-image src="/assets/methane-9.png" alt="Field LTC source plot showing true and predicted intermittent spikes" loading="lazy"></button><figcaption data-methane-caption>Field measurements · Figure 9 · LTC according to the source caption. Axes retained as supplied; units are not specified on this plot.</figcaption></figure><div class="readout" data-output aria-live="polite">Approximately four operational hours at one well. Surge timing is more closely captured than peak magnitude.</div></div>`;
case 'tourist-guide':return touristDemo();
case 'stock-research':return `<div class="demo" data-demo="video">${choices('Choose an implementation',['Flask / AJAX','Angular','Android'])}<div class="video-host"><div class="video-poster"><span class="eyebrow">Project recording / paper trading</span><h3 data-video-title>Flask / AJAX</h3><p>Stock research, watchlists and virtual trading.</p><div class="recording-actions"><a class="button primary" data-watch href="https://www.youtube.com/watch?v=oQRW5Dpfwks" target="_blank" rel="noopener noreferrer">Watch Flask / AJAX recording ↗</a><button data-play>Play embedded recording</button></div></div></div><p><a data-video-link href="https://www.youtube.com/watch?v=oQRW5Dpfwks" target="_blank" rel="noopener noreferrer">Open Flask / AJAX recording on YouTube ↗</a></p><p class="fine">Play the recording here, or open it on YouTube. If this browser blocks the player, a direct recording link remains available.</p></div>`;
case 'ecommerce':return `<div class="empty-state"><p class="eyebrow">Next iteration</p><h3>A working storefront, coming in a future build.</h3><p>The next demo will be a separate website build with products, a cart and order flows. The original project was course-based implementation practice.</p><a href="https://www.udemy.com/course/mean-stack-e-commerce-angular-nx-primeng/">Original course basis ↗</a></div>`;
default:return '';
}}
