export function peptideFilm(){return `<section class="peptide-film" id="peptide-pipeline" data-peptide-film aria-label="Animated peptide research pipeline">
<div class="film-heading"><div><p class="eyebrow">Inside the research pipeline</p><h3>Learn the pattern.<br>Design the sequence.</h3></div><p>Watch how a diffusion model learns, how a new sequence emerges, and how affinity prediction and agents connect the workflow.</p></div>
<label class="film-example">Saved example for decoding and prediction<select data-film-example aria-label="Animation candidate"></select></label>
<div class="film-player">
<div class="film-scene-heading"><span class="film-phase" data-film-phase>Offline training</span><span class="film-scene-index" data-film-index>01 / 07</span></div>
<h4 data-film-title>Start with a peptide library.</h4>
<div class="film-canvas-wrap"><canvas data-film-canvas aria-hidden="true"></canvas><noscript><p>Enable JavaScript to play the animation. The complete explanation is available in the transcript below.</p></noscript></div>
<div class="film-caption"><p data-film-caption>Experimental mRNA-display selection and sequencing supply peptide examples. Their amino-acid identities become numerical encodings for model training.</p><span data-film-equation>Selection → sequencing → encoding</span><p class="film-saved-result" data-film-result hidden></p></div>
<div class="film-route" data-film-route hidden><label for="film-route">Try a researcher request</label><select id="film-route" data-film-request><option value="both">Generate peptides and predict their affinity</option><option value="generate">Generate peptide candidates</option><option value="predict">Predict affinity for a supplied sequence</option></select><p data-film-route-note></p></div>
<div class="film-transport"><button data-film-play aria-label="Play pipeline animation">Play animation <span aria-hidden="true">▶</span></button><button data-film-replay aria-label="Replay pipeline animation">Replay ↺</button><label class="sr-only" for="film-seek">Animation timeline</label><input id="film-seek" data-film-seek type="range" min="0" max="56000" step="100" value="0"><output data-film-clock>0:00 / 0:56</output></div>
<p class="sr-only" data-film-status role="status"></p>
</div>
<div class="film-chapters" role="group" aria-label="Animation chapters">${['Library','Add noise','Learn','Denoise','Decode','CfC','Agents'].map((name,i)=>`<button data-film-chapter="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${name}</button>`).join('')}</div>
<p class="fine film-provenance">Conceptual animation, with a real saved candidate at the decoding and prediction stages. Noise, intermediate matrices and network motion explain the method; they are not recorded training states or model activations.</p>
<details class="film-transcript"><summary>Read the animation transcript and methods</summary>
<ol><li><strong>Library.</strong> Experimental collaborators supply mRNA-display selection data. Sequencing identifies amino-acid sequences, which become numerical training examples.</li><li><strong>Add noise.</strong> A training example is mixed with Gaussian noise at a sampled noise level. The added noise is known, so it provides a learning target.</li><li><strong>Learn.</strong> A neural denoiser receives the noisy encoding and its noise level. Its predicted noise is compared with the added noise; that error updates the model. Repeat across examples and noise levels. This is offline training, separate from generation.</li><li><strong>Denoise.</strong> Generation starts from fresh noise. The trained denoiser guides successive DDIM sampling steps toward a peptide encoding. The animation illustrates that progression and lands on the selected saved candidate; it does not recreate that candidate’s original sampling trajectory.</li><li><strong>Decode.</strong> The final encoding is converted to amino-acid identities. The explorer reconstructs a 20 × 20 one-hot representation of the selected saved sequence after removing its initial methionine. Its column ordering is alphabetical for readability.</li><li><strong>CfC.</strong> The Closed-form Continuous-time network processes the encoded sequence, carrying information between sequence positions. A regression readout predicts binding free energy, ΔG. The value shown is the selected candidate’s saved manuscript prediction; experimental measurement is displayed separately. The network graphic is a schematic, not a layer diagram or activation map.</li><li><strong>Agents.</strong> PydanticAI structures a researcher’s request; LangGraph selects generation, generation plus prediction, or prediction of a supplied sequence. The selected tools run and return sequences or affinity results. The workflow calls CfC inference directly. Training is not repeated for each request.</li></ol>
<p class="fine">Method references: <a href="https://arxiv.org/abs/2010.02502">Denoising Diffusion Implicit Models</a> · <a href="https://www.nature.com/articles/s42256-022-00556-7">Closed-form continuous-time neural networks</a>. Project evidence: <a href="/publications/#peptide">published peptide study</a> and the saved sequence-level affinity table described below.</p></details>
</section>`}
