(() => {
 const root=document.querySelector('[data-project-film]');if(!root)return;
 const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
 const film=JSON.parse($('[data-project-film-content]').textContent),kind=root.dataset.projectFilm;
 const canvas=$('[data-project-film-canvas]'),c=canvas.getContext('2d');if(!c)return;
 const motion=matchMedia('(prefers-reduced-motion: reduce)'),total=film.chapters.length*8000;
 let t=motion.matches?7999:0,playing=false,visible=false,raf=null,last=null,active=-1,W=900,H=370,scenario='normal';
 const mint='#bfe8d5',amber='#e9bc7a',muted='#a6c5bb',lineColor='#3c6059',images=new Map();
 const clamp=n=>Math.max(0,Math.min(1,n));
 function text(str,x,y,size=13,color=muted,align='center'){c.fillStyle=color;c.font=`${size}px "DM Sans",Arial,sans-serif`;c.textAlign=align;c.textBaseline='middle';c.fillText(str,x,y)}
 function line(x,y,xx,yy,color=lineColor,width=1){c.beginPath();c.moveTo(x,y);c.lineTo(xx,yy);c.lineWidth=width;c.strokeStyle=color;c.stroke()}
 function dot(x,y,r,color=mint){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=color;c.fill()}
 function box(x,y,w,h,stroke=lineColor){c.beginPath();c.roundRect(x,y,w,h,7);c.fillStyle='#133332';c.fill();c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}
 function link(x,y,xx,yy,p=1,color=mint){line(x,y,xx,yy);const a=Math.atan2(yy-y,xx-x);line(xx,yy,xx-6*Math.cos(a-.5),yy-6*Math.sin(a-.5),color);line(xx,yy,xx-6*Math.cos(a+.5),yy-6*Math.sin(a+.5),color);dot(x+(xx-x)*clamp(p),y+(yy-y)*clamp(p),3,color)}
 function labelBox(label,x,y,w,h=48,selected=false){box(x,y,w,h,selected?mint:lineColor);text(label,x+w/2,y+h/2,W<380?11:13,selected?mint:muted)}
 function flow(labels,p){const mobile=W<550,bw=mobile?Math.min(210,W-28):Math.min(160,(W-60)/labels.length-20),gap=mobile?64:24,start=mobile?(W-bw)/2:(W-labels.length*bw-(labels.length-1)*gap)/2;
  labels.forEach((s,i)=>{const x=mobile?start:start+i*(bw+gap),y=mobile?12+i*gap:138;labelBox(s,x,y,bw,46,i<=Math.floor(p*labels.length));if(i<labels.length-1)link(mobile?W/2:x+bw+4,mobile?y+50:y+23,mobile?W/2:x+bw+gap-4,mobile?y+61:y+23,clamp(p*labels.length-i))})}
 function recurrent(title,p){const cx=W/2,cy=165;box(cx-64,cy-28,128,56,mint);text(title,cx,cy,26,mint);c.beginPath();c.arc(cx,cy,89,-.8,Math.PI*1.8);c.strokeStyle=lineColor;c.stroke();const a=p*2*Math.PI;dot(cx+89*Math.cos(a),cy+89*Math.sin(a),4,amber);text('Context carried forward',cx,285,13);for(let i=0;i<7;i++){const x=cx+(i-3)*Math.min(28,W/9);dot(x,37,4,i<=p*7?mint:lineColor)}link(cx,52,cx,119,p)}
 function network(p,cx=W/2,cy=150){const width=Math.min(180,W*.62),nodes=[3,4,3].map((n,col)=>Array.from({length:n},(_,i)=>[cx-width/2+col*width/2,cy+(i-(n-1)/2)*34]));for(let k=0;k<2;k++)for(const a of nodes[k])for(const b of nodes[k+1])line(...a,...b);nodes.forEach((layer,k)=>layer.forEach(([x,y],i)=>dot(x,y,6,(i+k+Math.floor(p*5))%3===0?amber:mint)));text('Schematic network',cx,cy+90,12)}
 function texture(x,y,size,amount,offset=0){const cells=24,cell=size/cells;for(let r=0;r<cells;r++)for(let col=0;col<cells;col++){const z=Math.sin((r*91+col*47+offset)*1.7)*.5+.5,v=clamp((.5+.5*Math.cos(r*1.4+col*1.4))*(1-amount)+z*amount);c.fillStyle=`rgb(${20+v*160},${48+v*178},${50+v*165})`;c.fillRect(x+col*cell,y+r*cell,cell-1,cell-1)}}
 function source(src,caption){let img=images.get(src);if(!img){img=new Image();img.onload=draw;img.onerror=()=>{img.failed=true;draw()};img.src=src;images.set(src,img)}if(img.complete&&img.naturalWidth){const scale=Math.min((W-16)/img.naturalWidth,(H-60)/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;c.fillStyle='#fff';c.fillRect((W-w)/2,10,w,h);c.drawImage(img,(W-w)/2,10,w,h)}else{text(img.failed?'See the source figure below.':'Loading source image…',W/2,H/2,13)}text(caption,W/2,H-22,W<400?11:13)}
 function finance(s,p){
  const mobile=W<550,cols=mobile?2:3,bw=mobile?(W-32)/2:Math.min(195,(W-90)/3),gap=mobile?18:32,rows=mobile?3:2,totalWidth=cols*bw+(cols-1)*gap,start=(W-totalWidth)/2;
  const names=['Router','Retriever','Planner','Calculator','Verifier','Answer writer'],roles=['agent','tool + selection','agent','deterministic tool','checks','agent'];
  const order=mobile?[[0,0],[1,0],[1,1],[0,1],[0,2],[1,2]]:[[0,0],[1,0],[2,0],[2,1],[1,1],[0,1]];
  const pos=order.map(([x,y])=>[start+x*(bw+gap),30+y*(mobile?91:119)]),step=s===2&&p>.5?3:[0,1,2,4,5][s];
  for(let i=0;i<5;i++){const [x,y]=pos[i],[xx,yy]=pos[i+1],dx=Math.sign(xx-x),dy=Math.sign(yy-y);link(x+bw/2+dx*(bw/2+3),y+29+dy*33,xx+bw/2-dx*(bw/2+3),yy+29-dy*33,i<step?1:i===step?(s===2?p*2%1:p):0,i===step?amber:lineColor)}
  names.forEach((name,i)=>{const [x,y]=pos[i];box(x,y,bw,59,i===step?mint:lineColor);text(name,x+bw/2,y+22,mobile?11:14,i<=step?mint:muted);text(roles[i],x+bw/2,y+43,mobile?9:10,muted)});
  if(s===3&&scenario==='retry'){const a=pos[4],b=pos[1];c.beginPath();c.moveTo(a[0]+bw/2,a[1]);c.quadraticCurveTo(W/2,0,b[0]+bw/2,b[1]);c.strokeStyle=amber;c.setLineDash([4,4]);c.stroke();c.setLineDash([]);text(p<.5?'18.4 ≠ 128.4 − 112.0':'Retry → retrieve → plan → calculate',W/2,H-30,mobile?11:15,amber)}
  else text(['Question → numerical route','112.0 → 128.4  ·  USD millions','128.4 − 112.0 = 16.4','Years ✓   Units ✓   Arithmetic ✓','$16.4m increase  ·  14.64%'][s],W/2,H-30,mobile?12:19,mint);
 }
 function tem(s,p){if(s===0){const size=Math.min(238,W-40);texture((W-size)/2,34,size,.72,2);text('Noisy experimental observation · schematic',W/2,318,W<400?10:13);return}if(s===1){const size=Math.min(145,(W-42)/2),y=74;texture(10,y,size,.83,2);texture(W-size-10,y,size,.83,7);link(size+15,y+size/2,W-size-15,y+size/2,p);text('Paired recorruptions',W/2,280,16,mint);text('Both views are noisy',W/2,311,12);return}if(s===2){network(p);text('Paired input → DnCNN → training signal',W/2,302,W<400?11:15,mint);return}if(s===3){flow(['Upload image','Processing','Trained denoiser','Image + FFT report'],p);return}source('/assets/tem-pair.png','Original source panels · 1 nm scale bars')}
 function oil(s,p){if(s===5){source('/assets/oil-6.png','BEAP · original source figure');return}if(s===3){recurrent('LTC',p);return}if(s===4){const size=Math.min(208,W-48);texture((W-size)/2,35,size,1-p,13);text('Noise → forecast sample',W/2,289,17,mint);text('Conceptual diffusion process',W/2,321,12);return}
  const count=12,gap=5,size=Math.min(38,(W-32-gap*(count-1))/count),start=(W-(size+gap)*count+gap)/2,y=146;
  for(let i=0;i<count;i++){const x=start+i*(size+gap);box(x,y,size,55,i<8?lineColor:amber);if(i<8)line(x+size/2,y+15,x+size/2,y+40,mint,2);if(s===2&&i<8){const strength=(i+Math.floor(p*8))%4===0;c.beginPath();c.moveTo(x+size/2,y);c.quadraticCurveTo(W/2,30,W-35,146);c.strokeStyle=strength?mint:lineColor;c.stroke()}}
  if(s===0){['BEAP','BEAT','EUAT','EUZE'].forEach((name,i)=>text(name,W*(i+1)/5,77,W<400?10:15,mint));text('Site histories → time-ordered records',W/2,285,W<400?11:16)}
  else{text(s===2?'Selective connections · schematic':'Input history → future interval',W/2,283,W<400?11:16,mint);if(s===1){const x=start+Math.min(3,Math.floor(p*4))*(size+gap);c.strokeStyle=mint;c.lineWidth=2;c.strokeRect(x-3,y-7,5*(size+gap),69)}}text('History',W*.3,232,12);text('Forecast',W*.8,232,12,amber);
 }
 function bank(s,p){const bw=W-24,x=12;if(s===0){box(x,79,bw,125,mint);text('Show transactions',W/2,122,19,mint);text('above ₹1,000',W/2,158,24,amber);text('Customer question',W/2,263,13);return}if(s===1){['Intent: amount_filter','Comparison: above','Amount: 1000'].forEach((v,i)=>labelBox(v,x,34+i*85,bw,57,p*3>=i));return}if(s===2){flow(['Intent + entities','Flask webhook','Backend request','Result records'],p);return}
  const records=[['Coffee','₹180',false],['Books','₹1,450',true],['Groceries','₹2,100',true]],rowW=Math.min(W-28,530),rx=(W-rowW)/2;
  records.forEach(([label,value,match],i)=>{const y=43+i*73;box(rx,y,rowW,55,match&&p>(s===4?0:.2)?mint:lineColor);text(label,rx+14,y+27,14,match?mint:muted,'left');text(value,rx+rowW-14,y+27,16,match?amber:muted,'right')});text(s===4?'Books + Groceries → response':'Keep amounts above ₹1,000',W/2,312,W<400?12:18,mint);
 }
 function claims(s,p){if(s===0){box(12,47,W-24,174,mint);text('WhatsApp · forwarded claim',W/2,81,W<400?12:16,mint);text('“The city library',W/2,132,20);text('opens on Sunday.”',W/2,168,20);text('Fictional example',W/2,276,12);return}if(s===1){flow(['Forwarded text','Claim classifier','Claim candidate','Keywords'],p);return}if(s===2){const bw=W-24;['City · library · Sunday','A: Sunday opening hours','B: Membership rules'].forEach((s,i)=>labelBox(s,12,45+i*88,bw,56,i===1&&p>.3));return}if(s===3){const size=Math.min(92,W*.29),left=12,right=W-size-12;for(let i=0;i<8;i++){const y=66+i*20;c.fillStyle=mint;c.fillRect(left,y,size*(.25+((i*7)%9)/12),8);c.fillStyle=amber;c.fillRect(right,y,size*(.25+((i*5)%9)/12),8);link(left+size+6,y+4,right-6,y+4,p,i%2?lineColor:mint)}text('Claim',left+size/2,255,13);text('Article',right+size/2,255,13);text('Compare representations',W/2,304,16,mint);text('Schematic · no similarity scores',W/2,334,11);return}labelBox('Same topic ≠ proof of truth',12,56,W-24,65,true);labelBox('Read the supporting passage',12,155,W-24,65,p>.35);text('Similarity helps find evidence.',W/2,291,W<400?12:17,mint);text('Interpretation still matters.',W/2,323,13)}
 function english(s,p){if(s===0){labelBox('Topic: a recent project',12,45,W-24,56,true);labelBox('What did you build?',12,146,W-24,74,p>.25);text('Context → question generation',W/2,299,W<400?12:17,mint);return}if(s===1||s===3){const bars=40,dx=(W-32)/bars;for(let i=0;i<bars;i++){const quiet=i>12&&i<18||i>31,h=quiet?3:12+Math.abs(Math.sin(i*1.8))*(40+Math.sin(i*.3)*24);line(16+i*dx,140-h,16+i*dx,140+h,i/bars<=p?mint:lineColor,Math.max(1,dx*.55))}text(s===1?'Spoken answer → transcript':'Syllables · pauses · duration',W/2,257,W<400?12:18,mint);text('Schematic audio timeline',W/2,297,12);return}if(s===2){const bw=Math.min(W-20,550),x=(W-bw)/2;box(x,51,bw,82);text('Last month I build a model.',W/2,92,W<400?14:24);link(W/2,145,W/2,180,p,amber);box(x,192,bw,82,mint);text(p>.4?'Last month I built a model.':'Last month I … a model.',W/2,233,W<400?14:24,mint);text('build → built · past tense',W/2,321,15,amber);return}['Grammar: past-tense consistency','Speech: timing and pauses','Practice: describe a past project'].forEach((s,i)=>labelBox(s,10,34+i*90,W-20,64,p*3>=i))}
 function methane(s,p){if(s===0){const cx=W/2;line(cx-82,240,cx-65,101,mint,2);line(cx-65,101,cx+65,101,mint,2);line(cx+65,101,cx+82,240,mint,2);line(cx-99,241,cx+99,241);box(cx-15,201,30,40,amber);box(cx+30,127,35,30,mint);text('Sensor',cx+47,179,12);text('Well',cx,273,13);text('Canopy collection geometry',cx,315,W<400?12:17,mint);dot(cx+48,142,4,p>.4?amber:mint);return}if(s===1){recurrent('LTC / LSTM',p);text('Past measurements → forecast',W/2,330,W<400?11:15,mint);return}if(s===2){const size=Math.min(220,W-40),x=(W-size)/2,y=36;for(let i=0;i<9;i++){line(x+i*size/8,y,x+i*size/8,y+size);line(x,y+i*size/8,x+size,y+i*size/8)}labelBox('CFD',W/2-45,y+size/2-24,90,48,true);text('Simulation-generated time series',W/2,298,W<400?11:16,mint);text('Grid schematic · not a gas simulation',W/2,331,W<400?10:12);return}if(s===3){flow(['CFD data','FFN / LSTM / LTC','Predicted concentration','Offline comparison'],p);return}source('/assets/methane-9.png','Original LTC field result · axes retained')}
 function tour(s,p){if(s===0||s===2){source('/assets/bom-jesus.jpg',s===0?'Selected landmark photograph':'Basilica of Bom Jesus · prepared identity');return}if(s===1){network(p);text('Photo → visual features → class',W/2,294,W<400?11:17,mint);text('Conceptual CNN · not actual activations',W/2,327,W<400?10:12);return}if(s===3){const bw=Math.min(260,W-24),x=(W-bw)/2;box(x,18,bw,301,mint);text('Basilica of Bom Jesus',W/2,63,W<400?14:18,mint);for(let i=0;i<5;i++)line(x+22,110+i*23,x+bw-22-(i%2)*24,110+i*23,lineColor,3);box(W/2-28,249,56,44);text('QR',W/2,271,19,amber);return}const x=W*.25,xx=W*.75;dot(x,109,9,mint);dot(xx,222,9,amber);c.setLineDash([5,6]);line(x+12,119,xx-12,212,mint,2);c.setLineDash([]);text('Bom Jesus',x,79,W<400?11:16,mint);text('Sé Cathedral',xx,258,W<400?11:16,amber);text('Nearby places → external map',W/2,320,W<400?11:16);text('Conceptual link · not a geographic route',W/2,347,W<400?9:11)}
 const renders={finance,tem,oil,bank,claims,english,methane,tour};
 function draw(){const s=Math.min(film.chapters.length-1,Math.floor(t/8000)),p=clamp((t-s*8000)/8000);c.clearRect(0,0,W,H);const g=c.createRadialGradient(W/2,H/2,10,W/2,H/2,W*.7);g.addColorStop(0,'#193b39');g.addColorStop(1,'#0c2528');c.fillStyle=g;c.fillRect(0,0,W,H);renders[kind](s,p)}
 const stamp=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
 function sync(manual=false){const s=Math.min(film.chapters.length-1,Math.floor(t/8000));if(active!==s){active=s;$('[data-project-film-title]').textContent=film.chapters[s].title;$('[data-project-film-caption]').textContent=film.chapters[s].caption;$('[data-project-film-index]').textContent=`0${s+1} / 0${film.chapters.length}`;$$('[data-project-film-chapter]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===s)))}$('[data-project-film-seek]').value=String(t);$('[data-project-film-seek]').setAttribute('aria-valuetext',`${stamp(t)}, ${film.chapters[s].title}`);$('[data-project-film-clock]').textContent=`${stamp(t)} / ${stamp(total)}`;const play=$('[data-project-film-play]');play.textContent=motion.matches?'Next chapter →':playing?'Pause Ⅱ':t>=total?'Play again ↺':'Play animation ▶';play.setAttribute('aria-label',motion.matches?'Next workflow chapter':playing?'Pause workflow animation':'Play workflow animation');if(manual)$('[data-project-film-status]').textContent=`Chapter ${s+1}: ${film.chapters[s].title}`;draw()}
 function cancel(){if(raf!==null)cancelAnimationFrame(raf);raf=null;last=null}
 function schedule(){cancel();if(playing&&visible&&!document.hidden&&!motion.matches)raf=requestAnimationFrame(tick)}
 function tick(now){raf=null;if(last!==null)t=Math.min(total,t+Math.min(100,now-last));last=now;if(t>=total){playing=false;last=null}sync();if(playing&&visible&&!document.hidden&&!motion.matches)raf=requestAnimationFrame(tick)}
 function jump(s){playing=false;cancel();t=s*8000+(motion.matches?7999:0);sync(true)}
 $('[data-project-film-play]').addEventListener('click',()=>{if(motion.matches){jump((active+1)%film.chapters.length);return}playing=!playing;if(playing&&t>=total)t=0;sync();schedule()});
 $('[data-project-film-replay]').addEventListener('click',()=>{t=motion.matches?7999:0;playing=!motion.matches;sync(true);schedule()});
 $('[data-project-film-seek]').addEventListener('input',e=>{playing=false;cancel();t=Number(e.target.value);sync(true)});$$('[data-project-film-chapter]').forEach((b,i)=>b.addEventListener('click',()=>jump(i)));
 $('[data-project-film-scenario]')?.addEventListener('change',e=>{scenario=e.target.value;t=24000+(motion.matches?7999:0);playing=!motion.matches;sync(true);schedule()});
 document.addEventListener('visibilitychange',schedule);window.addEventListener('pagehide',()=>{playing=false;cancel()});motion.addEventListener('change',()=>{playing=false;cancel();if(motion.matches)t=active*8000+7999;sync(true)});
 new IntersectionObserver(([e])=>{visible=e.isIntersecting;schedule()},{threshold:.12}).observe(root);
 function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);c.setTransform(d,0,0,d,0,0);draw()}
 new ResizeObserver(resize).observe(canvas);sync();resize();
})();
