const chapter=(label,title,caption)=>({label,title,caption});
export const projectFilms={
 'financial-analyst':{kind:'finance',title:'Follow the agents.<br>Inspect the answer.',intro:'A question moves between specialized reasoning stages and deterministic tools, with evidence carried through every handoff.',note:'Reconstructed agent workflow using the fictional Northstar report. Agent roles are schematic; this is not a recorded execution or a claim that all stages run in parallel.',chapters:[
  chapter('Route','A question becomes a task.','The routing stage interprets “How much did total revenue increase?” and chooses the numerical path. LangGraph carries the question and shared workflow state between stages.'),
  chapter('Retrieve','Give the agents evidence.','Retrieval selects the Total revenue row: 112.0 for 2023 and 128.4 for 2024, both in USD millions. Row, year and unit references travel with the values.'),
  chapter('Plan','Turn reasoning into a bounded plan.','The planning agent specifies a subtraction with operands tied to those cells. It hands the plan to a deterministic calculator, which returns 128.4 − 112.0 = 16.4.'),
  chapter('Verify','Check before answering.','Verification checks arithmetic, available units and year coverage. A failed calculation returns to retrieval and planning for a bounded retry. Try the deliberate-error path to watch that handoff.'),
  chapter('Answer','Return the result with its source.','The answer writer receives the checked result: total revenue rose by $16.4 million, or 14.64%. Its source is Northstar report table 1. Arithmetic verification does not prove every interpretation correct.')],scenario:true},
 'tem-denoising':{kind:'tem',title:'Learn from noise.<br>Recover useful structure.',intro:'Follow self-supervised training, then see how a trained denoiser fits into a microscopy research workflow.',note:'Training textures and network motion are conceptual. The last chapter displays the supplied conference figure, preserving its original panels and scale bars. R2R is a reused method by Pang and collaborators.',chapters:[
  chapter('Observe','The experiment is already noisy.','Transmission Electron Microscopy (TEM) follows nanoscale structure during an experiment. Experimental collaborators supply noisy images; there is no measured clean version of each frame.'),
  chapter('Pair','Create training pairs from noisy data.','Recorrupted-to-Recorrupted (R2R) constructs paired observations by adding controlled noise under its noise assumptions. The paired views provide a learning signal without clean experimental targets.'),
  chapter('Train','Learn the denoising mapping.','A Denoising Convolutional Neural Network (DnCNN) learns from the paired recorruptions. Training is performed separately from the later upload-and-inference workflow.'),
  chapter('Use','Bring the model into a research portal.','An uploaded TEM image moves through processing and trained-model inference, then into an image-analysis report with denoised images and Fast Fourier Transform (FFT) analysis. This is a high-level workflow.'),
  chapter('Inspect','Return to the experimental evidence.','The original conference figure shows panels before and after denoising with 1 nm scale bars. Use the comparison and full source figures below to inspect detail; visual clarity alone does not establish that every feature is physical.')]},
 'oil-forecasting':{kind:'oil',title:'Read the history.<br>Model what changes.',intro:'Explore three forecasting approaches and the difference between an input history and the future interval being predicted.',note:'Timeline blocks and model motion explain concepts; they are not production measurements, attention weights or matched performance comparisons. The final panel is an unchanged source figure.',chapters:[
  chapter('History','Start with a production record.','BEAP, BEAT, EUAT and EUZE are oil-production site identifiers. Collaborators supplied the multi-well data and physics expertise; the records cover roughly four decades.'),
  chapter('Windows','Separate context from the forecast.','A model reads an input window to predict a future interval. Window length, sampling interval and forecast horizon determine the question being asked. The moving blocks illustrate that distinction without plotting invented measurements.'),
  chapter('Informer','Connect distant parts of the history.','Informer is a Transformer architecture for long-sequence forecasting. Its sparse-attention approach helps handle long histories. Connections here explain selective attention; they are not learned attention weights.'),
  chapter('LTC','Carry context as conditions change.','Liquid Time-constant (LTC) networks use adaptive continuous-time dynamics. The recurrent-state diagram explains information flow, not a measured physical reservoir state or a model activation.'),
  chapter('TimeGrad','Forecast with a diffusion approach.','The earlier preprint explores TimeGrad, a probabilistic forecasting method based on diffusion. This is an alternative model family, separate from the later LTC manuscript.'),
  chapter('Evidence','Inspect the source forecast.','The displayed BEAP figure comes from the later manuscript. Its model-specific axes are retained. The explorer below switches between all four sites and explains the Informer and LTC panels.')]},
 'banking-assistant':{kind:'bank',title:'Understand the question.<br>Build the right query.',intro:'Watch language become an intent, structured parameters, a filtered result and a readable response.',note:'Prepared explanation with fictional account records. Dialogflow handles intent and entities; this is an NLP assistant, not a multi-agent financial adviser.',chapters:[
  chapter('Question','A customer asks in everyday language.','“Show transactions above ₹1,000.” The interface sends the question into the language-understanding workflow.'),
  chapter('Understand','Extract intent and entities.','Dialogflow identifies an amount-filter intent and extracts the comparison “above” and amount 1000. These structured fields tell the backend which operation is needed.'),
  chapter('Query','Turn parameters into a request.','A Flask webhook maps the intent and fields to the appropriate backend request. Missing required fields trigger clarification rather than an assumed value.'),
  chapter('Filter','Keep records matching the question.','In this prepared browser example, two fictional transactions exceed ₹1,000: Books at ₹1,450 and Groceries at ₹2,100. The original application integrated banking APIs; the animation uses local sample records.'),
  chapter('Respond','Send a readable answer back.','The response returns through the application to the customer interface. The walkthrough below also covers recent transactions, dates and transaction status.')]},
 'semantic-claims':{kind:'claims',title:'From a forwarded claim<br>to relevant evidence.',intro:'Follow the WhatsApp pipeline through claim filtering, retrieval and semantic comparison, with a clear distinction between similarity and truth.',note:'Fictional claim and article excerpts. Embedding graphics and connecting lines are conceptual; no message data, model-computed vectors or similarity scores are fabricated.',chapters:[
  chapter('WhatsApp','Start with a forwarded message.','The study collected consenting WhatsApp Web messages, translated them to English and filtered forwarded messages by length. The short library message here is a readable illustration of the later stages.'),
  chapter('Claims','Identify claims worth checking.','A pretrained probabilistic LSTM dialogue-act classifier filtered candidate messages for claims. Keyword extraction then identified terms that could connect a claim to relevant news.'),
  chapter('Retrieve','Find candidate news articles.','Keyword overlap narrowed the news corpus. In the fictional example, “city”, “library” and “Sunday” connect the claim to an article about Sunday opening hours.'),
  chapter('Compare','Compare meaning, not just words.','Sentence-BERT encodes the claim and candidate articles. Cosine similarity compares their representations. The visual shows the comparison process, not actual embedding coordinates or computed scores.'),
  chapter('Interpret','Read what the evidence actually supports.','A retrieved article about Sunday opening concerns the same claim. An article about student fee waivers does not support “free for everyone.” Retrieval points to evidence; similarity alone does not establish truth.')]},
 'english-assistant':{kind:'english',title:'From a spoken answer<br>to focused practice.',intro:'Follow question generation, transcription, grammar edits and speech analysis through one prepared practice session.',note:'Prepared text and schematic speech graphics; no microphone recording or live speech assessment. The published method and retained app code use differing components, described in the project notes.',chapters:[
  chapter('Prompt','Give the learner something to say.','A topic and its context support question generation. Example: “What did you build, and what did you learn?” The published method discusses SynQG; retained app code includes a T5 question-generation pipeline.'),
  chapter('Speech','Capture an answer and its transcript.','The original workflow recorded spoken answers and transcribed them. This animation uses a prepared sentence and a schematic waveform, without capturing audio.'),
  chapter('Grammar','Turn token edits into a clearer sentence.','“Last month I build a model” becomes “Last month I built a model.” GECToR-style grammatical correction uses token transformations; the highlighted example explains a past-tense edit.'),
  chapter('Features','Look at the timing of speech.','Speech analysis examines syllables, pauses, speaking duration, rates and pitch summaries. The marks here explain those feature types, not a measured speaker or a validated ability score.'),
  chapter('Feedback','Give a specific practice focus.','The prepared report connects the edit to its reason: keep past-tense verbs consistent. Grammar feedback and speech features are separate signals; transcription errors alone do not prove pronunciation errors.')]},
 'methane-modeling':{kind:'methane',title:'Capture intermittent signals.<br>Study their dynamics.',intro:'See how field measurements and computational flow data support two distinct machine-learning tasks.',note:'Canopy, event marks and model diagrams are conceptual, not a gas simulation. The final chapter uses an original field source figure. No live monitoring or surrogate speedup is implied.',chapters:[
  chapter('Measure','Observe methane around a well.','Collaborators used a canopy and sensors to collect intermittent methane measurements at an abandoned well. Concentration measures methane in the sampled gas; it is different from mass emitted per unit time.'),
  chapter('Forecast','Learn patterns across a time window.','Offline sequence models use past measurements to predict subsequent concentration changes. LTC and LSTM source results captured surge timing more closely than peak magnitude; the field record was limited to about four operational hours at one well.'),
  chapter('Simulate','Keep the CFD task separate.','Computational Fluid Dynamics (CFD) supplies simulated flow and concentration data. Those data form a separate modeling task, not an extension of the field measurements.'),
  chapter('Approximate','Learn from simulation outputs.','FFN, LSTM and LTC results explore predicting concentration evolution from CFD-generated data. This motivates surrogate modeling, without establishing a measured computational speedup.'),
  chapter('Inspect','Compare with the recorded evidence.','The original LTC field figure is shown with its axes intact. Use the explorer below to inspect field and CFD panels separately, including the noted source-unit and caption inconsistencies.')]},
 'tourist-guide':{kind:'tour',title:'Recognize a landmark.<br>Open its story.',intro:'A real photo anchors an explanation of landmark recognition, information retrieval and the guide experience.',note:'Real licensed photo with prepared identification. Feature maps and CNN graphics are schematic; no live recognition model or confidence score is presented. Live inference remains a later addition.',chapters:[
  chapter('Photo','Start with what the visitor sees.','The visitor selects or captures a landmark photograph. This example uses a real photograph of the Basilica of Bom Jesus in Old Goa.'),
  chapter('Vision','Turn visual patterns into features.','A Convolutional Neural Network (CNN) learns visual patterns useful for landmark classification. The feature tiles explain that process; they are not actual feature maps from this photograph.'),
  chapter('Identify','Connect recognition to a landmark record.','The prepared identification is Basilica of Bom Jesus. In the original application, landmark recognition connected the image to its information record. No recognition is being computed in this preview.'),
  chapter('Guide','Make the identification useful.','The guide presents historical information and supports QR-linked text or audio for locations within a site. This portfolio supplies a text guide, without invented recordings.'),
  chapter('Explore','Continue the visit.','Nearby attractions and map navigation extend the experience beyond a name. The guide below links to Sé Cathedral on a map; no live location or route is calculated here.')],photo:true}
};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function projectFilm(id){const f=projectFilms[id];if(!f)return '';const duration=f.chapters.length*8;return `<section class="demo project-film" id="project-animation" data-project-film="${f.kind}" aria-label="Project workflow animation"><script type="application/json" data-project-film-content>${JSON.stringify(f)}</script><div class="film-heading"><div><p class="eyebrow">Watch the workflow</p><h3>${f.title}</h3></div><p>${f.intro}</p></div>${f.scenario?'<label class="film-example">Verification path<select data-project-film-scenario aria-label="Verification path"><option value="normal">Successful check</option><option value="retry">Deliberate error and retry</option></select></label>':''}<div class="film-player"><div class="film-scene-heading"><span class="film-phase">${f.kind==='finance'?'Agent handoffs & tools':'Conceptual process animation'}</span><span class="film-scene-index" data-project-film-index>01 / ${String(f.chapters.length).padStart(2,'0')}</span></div><h4 data-project-film-title>${f.chapters[0].title}</h4><div class="film-canvas-wrap"><canvas data-project-film-canvas aria-hidden="true"></canvas></div><div class="film-caption"><p data-project-film-caption>${f.chapters[0].caption}</p></div><div class="film-transport"><button data-project-film-play aria-label="Play workflow animation">Play animation ▶</button><button data-project-film-replay aria-label="Replay workflow animation">Replay ↺</button><label class="sr-only" for="project-film-seek">Workflow animation timeline</label><input id="project-film-seek" data-project-film-seek type="range" min="0" max="${duration*1000}" step="100" value="0"><output data-project-film-clock aria-live="off">0:00 / 0:${duration}</output></div><p class="sr-only" data-project-film-status role="status"></p></div><div class="film-chapters" role="group" aria-label="Workflow animation chapters">${f.chapters.map((c,i)=>`<button data-project-film-chapter="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${c.label}</button>`).join('')}</div><p class="fine film-provenance">${f.note}${f.photo?' Photo: <a href="https://commons.wikimedia.org/wiki/File:Fa%C3%A7ade_of_Basilica_of_Bom_Jesus.jpg">Bill william compton / Wikimedia Commons</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>, resized and uncropped.':''}</p><details class="film-transcript"><summary>Read the animation transcript</summary><ol>${f.chapters.map(c=>`<li><strong>${esc(c.title)}</strong> ${esc(c.caption)}</li>`).join('')}</ol></details></section>`}
