import {peptideFilm} from './peptide-film.mjs';
import fs from 'node:fs';
const peptides=JSON.parse(fs.readFileSync(new URL('./peptides.json',import.meta.url),'utf8'));
export const financialDemo=()=>`<div class="demo agent-demo" data-research="agents">
<p class="eyebrow">Inside the multi-agent workflow</p><h3>Follow the work between agents and tools.</h3><p>Choose a question, then inspect what each stage receives and produces. The workflow branches when a question needs a narrative answer, more evidence or clarification.</p>
<label class="field">Question for the analyst<select data-agent-question><option value="0">How much did total revenue increase?</option><option value="1">Which segment had the highest percentage growth?</option><option value="2">Summarize the revenue changes.</option><option value="3">What was adjusted profit?</option><option value="4">Follow a failed calculation check and retry.</option></select></label>
<div class="agent-layout"><div><p class="eyebrow">Workflow stages · select to inspect</p><div class="agent-nodes" data-agent-nodes></div></div><section class="agent-inspector" aria-live="polite" aria-atomic="true" data-agent-inspector></section></div>
<div class="demo-controls"><button data-agent-back>← Previous stage</button><span data-agent-position></span><button data-agent-next>Next stage →</button><button data-agent-reset>Restart</button></div>
<details open><summary>Report evidence · Northstar · USD millions</summary><div class="table-scroll" tabindex="0" aria-label="Report revenue table, scroll horizontally for both years"><table id="northstar-evidence"><caption>Fictional demonstration report · revenue table 1</caption><thead><tr><th>Metric</th><th>2023</th><th>2024</th></tr></thead><tbody>${[['total','Total revenue','112.0','128.4'],['industrial','Industrial','40.0','52.0'],['consumer','Consumer','42.0','46.0'],['services','Services','30.0','30.4']].map(([id,name,a,b])=>`<tr data-agent-row="${id}"><th>${name}</th><td id="${id}-2023">${a}</td><td id="${id}-2024">${b}</td></tr>`).join('')}</tbody></table></div></details>
<p class="fine">Prepared walkthrough of the implemented architecture using a fictional report. Agent responses are reconstructed examples; browser arithmetic is calculated locally. Stage names describe responsibilities, not a captured live execution trace.</p></div>`;
export const peptideDemo=()=>`<div class="demo peptide-demo" data-research="peptides">
<script type="application/json" data-peptide-records>${JSON.stringify(peptides)}</script>
${peptideFilm()}<div class="demo-divider"></div><p class="eyebrow">A real sequence, decoded</p><h3>See how a peptide becomes a model input.</h3><p>Choose a saved DDIM-generated candidate. The initial methionine (M) is removed for the 20-position encoding; each remaining amino acid occupies one column in its row.</p>
<label class="field">Saved candidate<select data-peptide-select>${peptides.map((p,i)=>`<option value="${i}">${p.id} · ${p.sequence}</option>`).join('')}</select></label>
<p class="fine">Full source sequence · initial M shown separately</p><div class="amino-sequence"><span class="initial-m" title="Initial methionine, removed for encoding">M</span><div data-amino-buttons></div></div>
<div class="encoding-layout"><div class="matrix-scroll" tabindex="0" aria-label="One-hot matrix, rows are sequence positions and columns are amino acids"><div class="encoding-matrix" data-matrix aria-hidden="true"></div></div><div class="readout" data-amino-inspector aria-live="polite"></div></div>
<label class="field">Decode the matrix, position by position<input type="range" data-decode min="0" max="20" value="20"><output data-decode-status>20 of 20 positions decoded</output></label><div class="decoded-sequence" data-decoded aria-live="polite"></div>
<p class="fine">Exact one-hot representation reconstructed from the saved sequence, with amino-acid columns ordered alphabetically. This shows encoding and decoding, not intermediate DDIM denoising states.</p>
<details class="source-details"><summary>Where these results come from</summary><p>The sequence-level table in the supplied affinity manuscript pairs each candidate with saved CfC predictions and experimental binding measurements. Selected records are reproduced here with permission; the manuscript itself is not a public download. Values retain the source’s displayed precision.</p><p>The study is in preparation. These examples use the saved manuscript model, not the later notebook’s three-seed aggregate evaluation. Candidate order follows the source table and is not a ranking.</p><p>ΔG: binding free energy in kcal/mol; more negative means stronger binding under comparable conditions. Kd: dissociation constant; lower means tighter binding. 1 pM = 10⁻¹² M.</p></details>
<div class="demo-divider"></div><h3>What the experiments showed</h3><div class="evidence-tabs" role="group" aria-label="Peptide experimental evidence"><button data-peptide-evidence="0" aria-pressed="true">Full-data experiment</button><button data-peptide-evidence="1" aria-pressed="false">Smaller-data experiment</button><button data-peptide-evidence="2" aria-pressed="false">Sequence novelty</button></div><div data-peptide-evidence-output aria-live="polite"></div>
<p class="fine">Experimental validation and sequence novelty are different measures. <a href="/publications/#peptide">Published DDIM study →</a></p></div>`;
export const touristDemo=()=>`<div class="demo" data-research="tourist"><p class="eyebrow">Explore a landmark · prepared photo walkthrough</p><div class="tourist-layout"><figure><img class="landmark-photo" src="/assets/bom-jesus.jpg" width="960" height="540" loading="lazy" alt="Photograph of the ornate stone facade of the Basilica of Bom Jesus in Old Goa"><figcaption>Photo: <a href="https://commons.wikimedia.org/wiki/File:Fa%C3%A7ade_of_Basilica_of_Bom_Jesus.jpg">Bill william compton / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a> · resized Commons rendition, uncropped.</figcaption></figure><section><div class="evidence-tabs" role="group" aria-label="Landmark walkthrough"><button data-tour-view="0" aria-pressed="true">Identify</button><button data-tour-view="1" aria-pressed="false">Read guide</button><button data-tour-view="2" aria-pressed="false">Explore nearby</button></div><div class="readout" data-tour-output aria-live="polite"><strong>Basilica of Bom Jesus</strong><p>Old Goa, India. This selected photo has a prepared identification; no recognition model is running.</p></div></section></div><p class="fine">Real photograph; selected-photo demonstration. Live image recognition is planned for a later iteration.</p></div>`;
